apiVersion: 1

datasources:
  - name: PlantRAG Postgres
    uid: plantrag-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: ${PG_HOST}
    database: ${PG_DB}
    user: ${PG_USER}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: true
